"""
Django settings for learning_site project.

Generated by 'django-admin startproject' using Django 1.8.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
from decouple import config
#from dj_database_url import parse as dburl
import dj_database_url

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

SECRET_KEY = config('SECRET_KEY')
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = ['mylearningsite.herokuapp.com']



# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'courses',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'learning_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates',],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [

                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'learning_site.wsgi.application'

#default_dburl = 'sqlite:///' + os.path.join(BASE_DIR, 'db.sqlite3')
# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
    'ENGINE': 'django.db.backends.mysql',
    'HOST': 'eu-cdbr-west-01.cleardb.com',
    'USER': 'bed2306b12d6df',
    'NAME': 'heroku_eddacf519ee66b1',
    'PASSWORD': 'acd7d16ad3478ec',


}
}



#DATABASES = {
#    'default': {
  # 'ENGINE': 'django.db.backends.sqlite3',
  # 'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),

#heroku addons:create cleardb:ignite --fork=mysql://root:root@localhost/test_database
#    'ENGINE': 'django.db.backends.mysql',
#    'NAME': 'test_database',
#    'USER': 'root',
#    'PASSWORD': 'root',
#    'HOST': 'localhost',
#    'PORT':'8889',

        #'ENGINE': 'django.db.backends.mysql',
        #'NAME': 'heroku_b187057ea7fba7f',
        #'USER': 'bf9d5d164e3a46',
        #'PASSWORD': 'd8df096c',
        #'HOST': 'localhost',
        #'PORT':'8889',

#mysql://bf9d5d164e3a46:d8df096c@eu-cdbr-west-01.cleardb.com/heroku_b187057ea7fba7f?reconnect=true

 # }
#}

#db_from_env = dj_database_url.config()
#DATABASES['default'].update(db_from_env)
#DATABASES = { 'default': config('DATABASE_URL', default=default_dburl, cast=dburl), }


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Los_Angeles'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = '/static/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')   #uplaod video put into media localxz
MEDIA_URL = '/media/'    #http browser

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'assets'),
)

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
