"""
Django settings for learning_site project.

Generated by 'django-admin startproject' using Django 1.8.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

from decouple import config
#from dj_database_url import parse as dburl
import dj_database_url
#from conf import *

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

SECRET_KEY = config('SECRET_KEY')
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = ['*']



# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'courses',
    'storages',
"ckeditor",
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'learning_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates',],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [

                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'learning_site.wsgi.application'

#default_dburl = 'sqlite:///' + os.path.join(BASE_DIR, 'db.sqlite3')
# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases
#
DATABASES = {
    'default': {
    'ENGINE': 'django.db.backends.mysql',
    'HOST': 'eu-cdbr-west-01.cleardb.com',
    'USER': 'bcda8ce4b492f3',
    'NAME': 'heroku_3b78fbf0c4e60da',
    'PASSWORD': '5bb797878509066',


}
}



#DATABASES = {
 #   'default': {
  # 'ENGINE': 'django.db.backends.sqlite3',
  # 'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
  #  }
#}
#heroku addons:create cleardb:ignite --fork=mysql://root:root@localhost/test_database
#    'ENGINE': 'django.db.backends.mysql',
#    'NAME': 'test_database',
#    'USER': 'root',
#    'PASSWORD': 'root',
#    'HOST': 'localhost',
#    'PORT':'8889',

        #'ENGINE': 'django.db.backends.mysql',
        #'NAME': 'heroku_b187057ea7fba7f',
        #'USER': 'bf9d5d164e3a46',
        #'PASSWORD': 'd8df096c',
        #'HOST': 'localhost',
        #'PORT':'8889',

#mysql://bf9d5d164e3a46:d8df096c@eu-cdbr-west-01.cleardb.com/heroku_b187057ea7fba7f?reconnect=true

 # }
#}

#db_from_env = dj_database_url.config()
#DATABASES['default'].update(db_from_env)
#DATABASES = { 'default': config('DATABASE_URL', default=default_dburl, cast=dburl), }


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Los_Angeles'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = '/static/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')   #uplaod video put into media localxz
MEDIA_URL = '/media/'    #http browser

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'assets'),
)

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
CKEDITOR_BASEPATH = "/my_static/ckeditor/ckeditor"


AWS_ACCESS_KEY_ID = 'AKIAJEW3XBL5RXLUV7VQ'
AWS_SECRET_ACCESS_KEY = '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'
AWS_STORAGE_BUCKET_NAME = 'mylearningsitebucket'


#MEDIA_URL = 'http://%s.s3.amazonaws.com/' % AWS_STORAGE_BUCKET_NAME
#MEDIA_URL = 'https://s3.console.aws.amazon.com/s3/buckets/mylearningsitebucket/?region=us-east-2'
#STATIC_URL = 'http://' + AWS_STORAGE_BUCKET_NAME + '.s3.amazonaws.com/'
#ADMIN_MEDIA_PREFIX = STATIC_URL + 'admin/'


# Tell django-storages that when coming up with the URL for an item in S3 storage, keep
# it simple - just use this domain plus the path. (If this isn't set, things get complicated).
# This controls how the `static` template tag from `staticfiles` gets expanded, if you're using it.
# We also use it in the next setting.
AWS_S3_CUSTOM_DOMAIN = '%s.s3.amazonaws.com' % AWS_STORAGE_BUCKET_NAME

AWS_LOCATION = 'static'
#MEDIAFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'


# This is used by the `static` template tag from `static`, if you're using that. Or if anything else
# refers directly to STATIC_URL. So it's safest to always set it.
#STATIC_URL = "https://%s/" % AWS_S3_CUSTOM_DOMAIN

# Tell the staticfiles app to use S3Boto storage when writing the collected static files (when
# you run `collectstatic`).
#STATICFILES_STORAGE = 'storages.backends.s3boto.S3BotoStorage'
MEDIAFILES_STORAGE = 'storages.backends.s3boto.S3BotoStorage'
#DEFAULT_FILE_STORAGE = 'learning_site.custom_storages.MediaStorage'
#DEFAULT_FILE_STORAGE = 'storages.backends.s3boto.S3Storage'

MEDIA_URL = 'http://s3-eu-west-1.amazonaws.com/%s' % AWS_STORAGE_BUCKET_NAME + '/'

#...
SITE_ID = 1

####################################
    ##  CKEDITOR CONFIGURATION ##
####################################

CKEDITOR_JQUERY_URL = 'https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js'

CKEDITOR_UPLOAD_PATH = 'uploads/'
CKEDITOR_IMAGE_BACKEND = "pillow"

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': None,
    },
}

###################################