# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-26 17:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('text', models.CharField(max_length=255)),
                ('correct', models.IntegerField(default=0)),
                ('selected', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(0)])),
                ('count', models.IntegerField(default=0)),
                ('text_version', models.IntegerField(default=1)),
                ('percentage_correct', models.IntegerField(default=0)),
                ('previous_version_percentage', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BackTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backtimes', models.IntegerField(default=0, null=True)),
                ('topic', models.CharField(max_length=255, null=True)),
                ('textversion', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('feeder', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0, null=True)),
                ('feedback', models.CharField(choices=[(b'BADLY EXPLAINED', b'Badly Explained'), (b'TO COMPLICATED', b'To Complicated'), (b'NOT INTERESTED', b'Not interesting'), (b'LOVED IT', b'Loved It!!!'), (b'WELL TAUGHT', b'Well Taught'), (b'GOOD MATERIAL', b'Good Material')], max_length=15)),
                ('textversion', models.IntegerField(default=0, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('prompt', models.TextField()),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('order', models.IntegerField(default=0, null=True)),
                ('total_questions', models.IntegerField(default=3)),
                ('total_answers', models.IntegerField(default=4)),
                ('correct', models.BooleanField(default=False)),
                ('answer_1', models.CharField(max_length=255)),
                ('answer_2', models.CharField(max_length=255)),
                ('answer_3', models.CharField(max_length=255)),
                ('answer_4', models.CharField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('order', models.IntegerField(default=0, null=True)),
                ('content', models.TextField(blank=True, default=b'', null=True)),
                ('video', models.FileField(null=True, upload_to=b'')),
                ('time', models.IntegerField(default=10, null=True)),
                ('version', models.IntegerField(default=1, null=True)),
                ('new', models.TextField(default=b'Noting new', null=True)),
                ('textversion', models.TextField(default=1, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MultipleChoiceQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courses.Question')),
                ('shuffle_answers', models.BooleanField(default=False)),
            ],
            bases=('courses.question',),
        ),
        migrations.CreateModel(
            name='TrueFalseQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courses.Question')),
            ],
            bases=('courses.question',),
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Quiz'),
        ),
        migrations.AddField(
            model_name='query',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Text'),
        ),
        migrations.AddField(
            model_name='backtime',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course'),
        ),
        migrations.AddField(
            model_name='backtime',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Text'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Question'),
        ),
    ]
